# Generated by Django 6.0 on 2025-12-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_is_verified_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
