# Generated by Django 6.0 on 2025-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('volunteer', 'Volunteer'), ('donor', 'Donor'), ('staff', 'Staff')], max_length=50),
        ),
    ]
